# Generated by Django 3.1.2 on 2020-12-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_ourdrinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourdrinks',
            name='temperature',
        ),
        migrations.AddField(
            model_name='ourdrinks',
            name='temperature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinks.temperature'),
        ),
        migrations.RemoveField(
            model_name='ourdrinks',
            name='toppings',
        ),
        migrations.AddField(
            model_name='ourdrinks',
            name='toppings',
            field=models.ManyToManyField(to='drinks.Topping'),
        ),
        migrations.RemoveField(
            model_name='splash',
            name='ice',
        ),
        migrations.AddField(
            model_name='splash',
            name='ice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinks.ice'),
        ),
        migrations.RemoveField(
            model_name='splash',
            name='sizes',
        ),
        migrations.AddField(
            model_name='splash',
            name='sizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinks.size'),
        ),
        migrations.RemoveField(
            model_name='splash',
            name='sugar',
        ),
        migrations.AddField(
            model_name='splash',
            name='sugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinks.sugar'),
        ),
        migrations.RemoveField(
            model_name='splash',
            name='temperature',
        ),
        migrations.AddField(
            model_name='splash',
            name='temperature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinks.temperature'),
        ),
    ]
